version: "3.8"

services:
  echtzeitkiosk-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/echtzeitsysteme/echtzeitkiosk-frontend:arm64
    # image: ghcr.io/echtzeitsysteme/echtzeitkiosk-frontend:amd64
    container_name: echtzeitkiosk-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    
    expose:
      - '80'
    # ports:
    #   - '80:80'

    networks:
      - proxy
      - default

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # routers
      - "traefik.http.routers.echtzeitkiosk-frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.echtzeitkiosk-frontend-secure.rule=Host(`echtzeitkiosk.mertalpulus.eu`)"
      - "traefik.http.routers.echtzeitkiosk-frontend-secure.service=echtzeitkiosk-frontend"
      # services
      - "traefik.http.services.echtzeitkiosk-frontend.loadbalancer.server.port=80"

    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

    logging:
      driver: "json-file"
      options:
        max-size: "512m"

networks:
  proxy:
    external: true
